### ISSUE TITLE
share steps to recreate system art?

### ISSUE THREAD

**Issue by ahmadnassri** [Mntz/muOS-EpicNoir#1]
I have some extra systems that you don't have listed, would be great if you share your steps to re-create the right sizes? or did you do them manually?

**Comment by Mntz** [comment]
Hello, it's by hand. A template file and steps are available: https://github.com/Mntz/muOS-EpicNoir/tree/main/folderart

You can also request extra art via Discord.

**Comment by ahmadnassri** [comment]
ah perfect, I somehow missed the .psd file!

thanks
